In [1]:
import os
import pandas as pd

### Load images that are more than 3 times in corpus

In [5]:
path = r'C:\Users\Orion\Documents\Projets\CERES\ScrappingTwitter\resources'
df = pd.read_csv(os.path.join(path, 'pma_images_multiple_occurences.csv'), header=0, sep=',')
df

,sha1,created_at,from_user_name
0,ffff9b90e8dce13857e3bef7389e50ed5eb648a7,2019-09-26 13:49:23,josephinemd34
1,ffff9b90e8dce13857e3bef7389e50ed5eb648a7,2019-09-27 06:31:17,ClPeqt
2,ffff9b90e8dce13857e3bef7389e50ed5eb648a7,2019-09-26 17:46:36,JulietteLauzza
3,ffff9b90e8dce13857e3bef7389e50ed5eb648a7,2019-09-26 13:45:58,MaKarDoue
4,ffff9b90e8dce13857e3bef7389e50ed5eb648a7,2019-09-27 07:27:31,06aime
...,...,...,...
261007,0008255f72057dbf97e229199e6595e2deebecfd,2019-10-06 10:36:34,O_de_Clisson
261008,0008255f72057dbf97e229199e6595e2deebecfd,2019-10-06 10:30:59,ManifPourTous89
261009,0008255f72057dbf97e229199e6595e2deebecfd,2019-10-06 11:22:15,vaubandaniel
261010,0008255f72057dbf97e229199e6595e2deebecfd,2019-10-06 10:32:13,albdmt
261011,0008255f72057dbf97e229199e6595e2deebecfd,2019-10-06 10:38:04,VotezPoisson

### order values by date

In [10]:
df["created_at"] = pd.to_datetime(df["created_at"])
# keep only date and not time
df["created_at"] = df["created_at"].dt.date
df = df.sort_values(by="created_at")

                                            sha1  created_at   from_user_name
14865   ed732ab07f2cbb0ec7a030bf2e5aaa3e2c0089c5  2019-08-28  AlaouiMoualaoui
97304   9ec90ff173cacf392f8f03f33fe3f2cf7061d618  2019-08-28     Arnaud_38000
48779   cf44e461bcfb2d6fb50b8454f6c7881377727443  2019-08-28   AllianceVita34
124032  838c857d07ee0dce852ca22c2555e2fdeeb3c8b2  2019-08-28      JoycenoaNoa
197820  3d007650564cee0febd894fc958409803b689a2c  2019-08-28      BeaulieuBap
...                                          ...         ...              ...
51219   cc0417ee078d6b661b7db5e4f8fd44969bea6c2d  2021-08-21         RDelinfo
117080  8a7232c3f9b1649d947b5fc565d11ed0705b12b5  2021-08-23         rotreuil
66252   bb5ba917fe22b4e6e6a2458c00106007f9c94705  2021-08-26       le_stoique
144527  7009158eae27715fdd1f20e0db156cfbca589635  2021-08-27    Fests_infobot
84116   ad1aa06048c4dbb4d6975fc1879fa36511efc338  2021-08-31         BGuirlet

[261012 rows x 3 columns]

### build skeletton from df

In [11]:
from datetime import date, timedelta

start_date = df['created_at'].iloc[0]
end_date = df['created_at'].iloc[-1]
delta = timedelta(days=1)
while start_date <= end_date:
    print(start_date.strftime("%Y-%m-%d"))
    start_date += delta

2019-08-28
2019-08-29
2019-08-30
2019-08-31
2019-09-01
2019-09-02
2019-09-03
2019-09-04
2019-09-05
2019-09-06
2019-09-07
2019-09-08
2019-09-09
2019-09-10
2019-09-11
2019-09-12
2019-09-13
2019-09-14
2019-09-15
2019-09-16
2019-09-17
2019-09-18
2019-09-19
2019-09-20
2019-09-21
2019-09-22
2019-09-23
2019-09-24
2019-09-25
2019-09-26
2019-09-27
2019-09-28
2019-09-29
2019-09-30
2019-10-01
2019-10-02
2019-10-03
2019-10-04
2019-10-05
2019-10-06
2019-10-07
2019-10-08
2019-10-09
2019-10-10
2019-10-11
2019-10-12
2019-10-13
2019-10-14
2019-10-15
2019-10-16
2019-10-17
2019-10-18
2019-10-19
2019-10-20
2019-10-21
2019-10-22
2019-10-23
2019-10-24
2019-10-25
2019-10-26
2019-10-27
2019-10-28
2019-10-29
2019-10-30
2019-10-31
2019-11-01
2019-11-02
2019-11-03
2019-11-04
2019-11-05
2019-11-06
2019-11-07
2019-11-08
2019-11-09
2019-11-10
2019-11-11
2019-11-12
2019-11-13
2019-11-14
2019-11-15
2019-11-16
2019-11-17
2019-11-18
2019-11-19
2019-11-20
2019-11-21
2019-11-22
2019-11-23
2019-11-24
2019-11-25
2019-11-26
2019-11-27
2019-11-28
2019-11-29
2019-11-30
2019-12-01
2019-12-02
2019-12-03
2019-12-04
2019-12-05
2019-12-06
2019-12-07
2019-12-08
2019-12-09
2019-12-10
2019-12-11
2019-12-12
2019-12-13
2019-12-14
2019-12-15
2019-12-16
2019-12-17
2019-12-18
2019-12-19
2019-12-20
2019-12-21
2019-12-22
2019-12-23
2019-12-24
2019-12-25
2019-12-26
2019-12-27
2019-12-28
2019-12-29
2019-12-30
2019-12-31
2020-01-01
2020-01-02
2020-01-03
2020-01-04
2020-01-05
2020-01-06
2020-01-07
2020-01-08
2020-01-09
2020-01-10
2020-01-11
2020-01-12
2020-01-13
2020-01-14
2020-01-15
2020-01-16
2020-01-17
2020-01-18
2020-01-19
2020-01-20
2020-01-21
2020-01-22
2020-01-23
2020-01-24
2020-01-25
2020-01-26
2020-01-27
2020-01-28
2020-01-29
2020-01-30
2020-01-31
2020-02-01
2020-02-02
2020-02-03
2020-02-04
2020-02-05
2020-02-06
2020-02-07
2020-02-08
2020-02-09
2020-02-10
2020-02-11
2020-02-12
2020-02-13
2020-02-14
2020-02-15
2020-02-16
2020-02-17
2020-02-18
2020-02-19
2020-02-20
2020-02-21
2020-02-22
2020-02-23
2020-02-24
2020-02-25
2020-02-26
2020-02-27
2020-02-28
2020-02-29
2020-03-01
2020-03-02
2020-03-03
2020-03-04
2020-03-05
2020-03-06
2020-03-07
2020-03-08
2020-03-09
2020-03-10
2020-03-11
2020-03-12
2020-03-13
2020-03-14
2020-03-15
2020-03-16
2020-03-17
2020-03-18
2020-03-19
2020-03-20
2020-03-21
2020-03-22
2020-03-23
2020-03-24
2020-03-25
2020-03-26
2020-03-27
2020-03-28
2020-03-29
2020-03-30
2020-03-31
2020-04-01
2020-04-02
2020-04-03
2020-04-04
2020-04-05
2020-04-06
2020-04-07
2020-04-08
2020-04-09
2020-04-10
2020-04-11
2020-04-12
2020-04-13
2020-04-14
2020-04-15
2020-04-16
2020-04-17
2020-04-18
2020-04-19
2020-04-20
2020-04-21
2020-04-22
2020-04-23
2020-04-24
2020-04-25
2020-04-26
2020-04-27
2020-04-28
2020-04-29
2020-04-30
2020-05-01
2020-05-02
2020-05-03
2020-05-04
2020-05-05
2020-05-06
2020-05-07
2020-05-08
2020-05-09
2020-05-10
2020-05-11
2020-05-12
2020-05-13
2020-05-14
2020-05-15
2020-05-16
2020-05-17
2020-05-18
2020-05-19
2020-05-20
2020-05-21
2020-05-22
2020-05-23
2020-05-24
2020-05-25
2020-05-26
2020-05-27
2020-05-28
2020-05-29
2020-05-30
2020-05-31
2020-06-01
2020-06-02
2020-06-03
2020-06-04
2020-06-05
2020-06-06
2020-06-07
2020-06-08
2020-06-09
2020-06-10
2020-06-11
2020-06-12
2020-06-13
2020-06-14
2020-06-15
2020-06-16
2020-06-17
2020-06-18
2020-06-19
2020-06-20
2020-06-21
2020-06-22
2020-06-23
2020-06-24
2020-06-25
2020-06-26
2020-06-27
2020-06-28
2020-06-29
2020-06-30
2020-07-01
2020-07-02
2020-07-03
2020-07-04
2020-07-05
2020-07-06
2020-07-07
2020-07-08
2020-07-09
2020-07-10
2020-07-11
2020-07-12
2020-07-13
2020-07-14
2020-07-15
2020-07-16
2020-07-17
2020-07-18
2020-07-19
2020-07-20
2020-07-21
2020-07-22
2020-07-23
2020-07-24
2020-07-25
2020-07-26
2020-07-27
2020-07-28
2020-07-29
2020-07-30
2020-07-31
2020-08-01
2020-08-02
2020-08-03
2020-08-04
2020-08-05
2020-08-06
2020-08-07
2020-08-08
2020-08-09
2020-08-10
2020-08-11
2020-08-12
2020-08-13
2020-08-14
2020-08-15
2020-08-16
2020-08-17
2020-08-18
2020-08-19
2020-08-20
2020-08-21
2020-08-22
2020-08-23
2020-08-24
2020-08-25
2020-08-26
2020-08-27
2020-08-28
2020-08-29
2020-08-30
2020-08-31
2020-09-01
2020-09-02
2020-09-03
2020-09-04
2020-09-05
2020-09-06
2020-09-07
2020-09-08
2020-09-09
2020-09-10
2020-09-11
2020-09-12
2020-09-13
2020-09-14
2020-09-15
2020-09-16
2020-09-17
2020-09-18
2020-09-19
2020-09-20
2020-09-21
2020-09-22
2020-09-23
2020-09-24
2020-09-25
2020-09-26
2020-09-27
2020-09-28
2020-09-29
2020-09-30
2020-10-01
2020-10-02
2020-10-03
2020-10-04
2020-10-05
2020-10-06
2020-10-07
2020-10-08
2020-10-09
2020-10-10
2020-10-11
2020-10-12
2020-10-13
2020-10-14
2020-10-15
2020-10-16
2020-10-17
2020-10-18
2020-10-19
2020-10-20
2020-10-21
2020-10-22
2020-10-23
2020-10-24
2020-10-25
2020-10-26
2020-10-27
2020-10-28
2020-10-29
2020-10-30
2020-10-31
2020-11-01
2020-11-02
2020-11-03
2020-11-04
2020-11-05
2020-11-06
2020-11-07
2020-11-08
2020-11-09
2020-11-10
2020-11-11
2020-11-12
2020-11-13
2020-11-14
2020-11-15
2020-11-16
2020-11-17
2020-11-18
2020-11-19
2020-11-20
2020-11-21
2020-11-22
2020-11-23
2020-11-24
2020-11-25
2020-11-26
2020-11-27
2020-11-28
2020-11-29
2020-11-30
2020-12-01
2020-12-02
2020-12-03
2020-12-04
2020-12-05
2020-12-06
2020-12-07
2020-12-08
2020-12-09
2020-12-10
2020-12-11
2020-12-12
2020-12-13
2020-12-14
2020-12-15
2020-12-16
2020-12-17
2020-12-18
2020-12-19
2020-12-20
2020-12-21
2020-12-22
2020-12-23
2020-12-24
2020-12-25
2020-12-26
2020-12-27
2020-12-28
2020-12-29
2020-12-30
2020-12-31
2021-01-01
2021-01-02
2021-01-03
2021-01-04
2021-01-05
2021-01-06
2021-01-07
2021-01-08
2021-01-09
2021-01-10
2021-01-11
2021-01-12
2021-01-13
2021-01-14
2021-01-15
2021-01-16
2021-01-17
2021-01-18
2021-01-19
2021-01-20
2021-01-21
2021-01-22
2021-01-23
2021-01-24
2021-01-25
2021-01-26
2021-01-27
2021-01-28
2021-01-29
2021-01-30
2021-01-31
2021-02-01
2021-02-02
2021-02-03
2021-02-04
2021-02-05
2021-02-06
2021-02-07
2021-02-08
2021-02-09
2021-02-10
2021-02-11
2021-02-12
2021-02-13
2021-02-14
2021-02-15
2021-02-16
2021-02-17
2021-02-18
2021-02-19
2021-02-20
2021-02-21
2021-02-22
2021-02-23
2021-02-24
2021-02-25
2021-02-26
2021-02-27
2021-02-28
2021-03-01
2021-03-02
2021-03-03
2021-03-04
2021-03-05
2021-03-06
2021-03-07
2021-03-08
2021-03-09
2021-03-10
2021-03-11
2021-03-12
2021-03-13
2021-03-14
2021-03-15
2021-03-16
2021-03-17
2021-03-18
2021-03-19
2021-03-20
2021-03-21
2021-03-22
2021-03-23
2021-03-24
2021-03-25
2021-03-26
2021-03-27
2021-03-28
2021-03-29
2021-03-30
2021-03-31
2021-04-01
2021-04-02
2021-04-03
2021-04-04
2021-04-05
2021-04-06
2021-04-07
2021-04-08
2021-04-09
2021-04-10
2021-04-11
2021-04-12
2021-04-13
2021-04-14
2021-04-15
2021-04-16
2021-04-17
2021-04-18
2021-04-19
2021-04-20
2021-04-21
2021-04-22
2021-04-23
2021-04-24
2021-04-25
2021-04-26
2021-04-27
2021-04-28
2021-04-29
2021-04-30
2021-05-01
2021-05-02
2021-05-03
2021-05-04
2021-05-05
2021-05-06
2021-05-07
2021-05-08
2021-05-09
2021-05-10
2021-05-11
2021-05-12
2021-05-13
2021-05-14
2021-05-15
2021-05-16
2021-05-17
2021-05-18
2021-05-19
2021-05-20
2021-05-21
2021-05-22
2021-05-23
2021-05-24
2021-05-25
2021-05-26
2021-05-27
2021-05-28
2021-05-29
2021-05-30
2021-05-31
2021-06-01
2021-06-02
2021-06-03
2021-06-04
2021-06-05
2021-06-06
2021-06-07
2021-06-08
2021-06-09
2021-06-10
2021-06-11
2021-06-12
2021-06-13
2021-06-14
2021-06-15
2021-06-16
2021-06-17
2021-06-18
2021-06-19
2021-06-20
2021-06-21
2021-06-22
2021-06-23
2021-06-24
2021-06-25
2021-06-26
2021-06-27
2021-06-28
2021-06-29
2021-06-30
2021-07-01
2021-07-02
2021-07-03
2021-07-04
2021-07-05
2021-07-06
2021-07-07
2021-07-08
2021-07-09
2021-07-10
2021-07-11
2021-07-12
2021-07-13
2021-07-14
2021-07-15
2021-07-16
2021-07-17
2021-07-18
2021-07-19
2021-07-20
2021-07-21
2021-07-22
2021-07-23
2021-07-24
2021-07-25
2021-07-26
2021-07-27
2021-07-28
2021-07-29
2021-07-30
2021-07-31
2021-08-01
2021-08-02
2021-08-03
2021-08-04
2021-08-05
2021-08-06
2021-08-07
2021-08-08
2021-08-09
2021-08-10
2021-08-11
2021-08-12
2021-08-13
2021-08-14
2021-08-15
2021-08-16
2021-08-17
2021-08-18
2021-08-19
2021-08-20
2021-08-21
2021-08-22
2021-08-23
2021-08-24
2021-08-25
2021-08-26
2021-08-27
2021-08-28
2021-08-29
2021-08-30
2021-08-31

In [31]:
res = df.loc[df['created_at'] == df.iloc[0]['created_at']].groupby('sha1', as_index=False).count()

In [45]:
df.loc[df['sha1'] == '3e78381d49834fac28ff3e0d541341227b887592']

                                            sha1  created_at   from_user_name
192653  3e78381d49834fac28ff3e0d541341227b887592  2020-04-28     ____Sha_____
194085  3e78381d49834fac28ff3e0d541341227b887592  2020-04-28      viiesurnous
193269  3e78381d49834fac28ff3e0d541341227b887592  2020-04-28        celia_rfd
192128  3e78381d49834fac28ff3e0d541341227b887592  2020-04-28  LapointeBoumed1
193268  3e78381d49834fac28ff3e0d541341227b887592  2020-04-28        MrDridrix
...                                          ...         ...              ...
194506  3e78381d49834fac28ff3e0d541341227b887592  2020-05-30    ibrahim_cr678
193718  3e78381d49834fac28ff3e0d541341227b887592  2020-06-07      andromed_a_
193843  3e78381d49834fac28ff3e0d541341227b887592  2020-06-12    slytherinzone
194277  3e78381d49834fac28ff3e0d541341227b887592  2020-09-16        audic_212
195122  3e78381d49834fac28ff3e0d541341227b887592  2020-11-01    IzlayBeckford

[4654 rows x 3 columns]

In [32]:
res

                                        sha1  created_at  from_user_name
0   001602fbfda6d51315bbb0c7257d564410b14189           6               6
1   01ec35a3621f39c9505f10d4e39a61005630c3ae           1               1
2   065b2a560c1d6e12cd5f0e758bb882a6ad4d6358           5               5
3   0ac599d30558d7bc8b75fb519685e6bb733f5311           3               3
4   0b906c97936d19baa3ae533c1563e825f5f8e977         153             153
..                                       ...         ...             ...
75  f0c983ed65b22f8f47f2cba38c7d30851f9c789e           3               3
76  f332579af5961cde45fb885c6abc3a28899733a8           8               8
77  f42850ea933eab1bc9ca89dc30f3ec1e6682a0ce           3               3
78  f54551df90c62ea02a7bcab085fb869706c9e95b           1               1
79  fe74965ad7ac95a04c83817c1a50379cdbdb16d6           9               9

[80 rows x 3 columns]

In [34]:
for index, line in res.iterrows():
    print(line['sha1'])

001602fbfda6d51315bbb0c7257d564410b14189
01ec35a3621f39c9505f10d4e39a61005630c3ae
065b2a560c1d6e12cd5f0e758bb882a6ad4d6358
0ac599d30558d7bc8b75fb519685e6bb733f5311
0b906c97936d19baa3ae533c1563e825f5f8e977
0c068646a0f93f24fd875da3b12948232508fa5b
12fcb78d70f17ed9233c68050c25550c3f649ff8
16b8675aee8968c31ae2d91154ef8511437a16cb
1c6ea12fe1b3a79e22ed4f55ffbb20506db8857c
1f10ebb7e0a4ee8fe26f30a113d9976682178860
1f39605a7e6d7762079f719b5ca3ca6d6b29c58d
20f50055074fe039f140d5ffbdb11b059763b2ea
238ac74907aca493c2582519b63522bdf4f2cf62
2ccc86cc9f310bfdcd85692af4a114e539e0737c
31b2b7b83adce8e8fe06cdeb276d32d0d1fd3b8a
31cbfae914abf95d899b4ec203ad162b2004f0e7
353b90983e58d52a15ea07597fcadd6b67db226e
356b87ff21e03c98436bee1e0c9c6e0da469e301
35f17f069db455c5c3f3ba6f9d8e4d75c59bd21a
37226b52087f202f6b3586aa04a9de060e126cfa
3921ddca6ce3679f9920bc9728a14bec35a6bc28
3cef6a280581af2b29f722182d442b62a7cef92c
3d007650564cee0febd894fc958409803b689a2c
3e0d870f433db40ec0f7d82a995a801c4259320b
3fd0fddeb47bfb0541ef02dc63cbe76aff860db0
42eb4cac65c61956ef6abf076a31ec7fe22e91b8
5d5fb8e8b13979d7a8e693ce508ebb08fb665303
5f13588436087825fed5b90905522ee4871977c2
6a99f534230532814ada20fd81bacbf5504e99ca
6c1daa6c7be764c584cff9b658450ee5ac7c1f36
6d8667e61076df8d9c562814dc371cbf06064678
6fb4bf0c6fad5a8ada58ca114a3954820f6e78fd
7330802986492dd3bac3aaf95c1d60d1b74b0497
7564a3311b01b01e431661b768a4c568ac7d6358
765e2abb5219621b5037f6f474e0fb3ba63e10ce
7820bbd34afd88056b1e3f3fe7dd85ae845ea075
78411a7b32d7c7a47eedf6fd2e709ba8998981ef
790e635e08d96dbb8c52a470f45393acf4115dea
7f6d933b6755e3645929cb986f4cebdcfe7fc93e
82dd053cb12b2dc79556b57b083f35fe183bbe5d
838c857d07ee0dce852ca22c2555e2fdeeb3c8b2
86a0e31949fa779409b3c09788752d23eeb2e760
9659cf7232086ea86e873b231fc15b38c3e5c1a5
9939ca88bdb865e92e2300ef50c1e085d266856a
9a7e16d9d675a37f5ed320f5d317ddaa4fb2f199
9ec90ff173cacf392f8f03f33fe3f2cf7061d618
a57166aa6f24df421ceb9f85ef3a318636bc32f2
a66fdc2692a09ea9915cba6ec8a939c0f027532c
a7611ece1b07d57dd89de6a442d15d1f3b341cba
a81a902ba6beb1fda1ebdbc8f64eff971737c9d9
ab4d94745a111163f44164b867bf7431079bb7fd
ae5d2300c063cce9ecdad73454544598063c9a93
b0c62240e41b58b6cbec0617509418686ec66968
b1b943e48206e45e465eea28617632c5dac529d3
b826170ef9579556a99c6c0390bd2d94bd3d2982
bdc8c54d497cfdb36c38874fe1d24a32784261a1
bfdcece687807ccc3cecc29810417bc3ef8119a3
c365ccaa3749ddd466f698a980d95a8766d4a4a6
c8f65823c32befb6f18a9f83bbf466fceb3b7be2
cc02687a2d75f36f036c1e6770102540caf60460
cf44e461bcfb2d6fb50b8454f6c7881377727443
cf5cde657b69049ae806cc116e65a4e11c426325
cff014c8254a6785be2ee85cec85f7e3b44ac693
d0b8305f159a20bac1919a1a6b7f49806ad8d70a
d2d6a03a2ad59541cc7e12cfce65103d561294be
d6c843c3ef491336a188b051181ff340835cf870
d6ecf21135b245235c12aab1f5f34adbf31c6f0e
d855f85671383b773793dec4c8ace5000b7ade54
ddec76dd2354b2f79dc6823c3f990fa70534b324
e312a6d15f59061a6c329e1cb377fec6b0879830
e46315db1e1a9ff30b2a1bb897a35f99edd5822d
e692541621a4832f9c449026d8dc949053448d22
e83ade91c9680d79db154b1cd65424dcd05be770
ed732ab07f2cbb0ec7a030bf2e5aaa3e2c0089c5
edadfa630628d4468226778eb7a5b7e59157a389
f0c983ed65b22f8f47f2cba38c7d30851f9c789e
f332579af5961cde45fb885c6abc3a28899733a8
f42850ea933eab1bc9ca89dc30f3ec1e6682a0ce
f54551df90c62ea02a7bcab085fb869706c9e95b
fe74965ad7ac95a04c83817c1a50379cdbdb16d6

In [43]:
def build_skeletton(df):
    start_date = df['created_at'].iloc[0]
    end_date = df['created_at'].iloc[-1]
    nodes = "Id;Label"
    nodes_dic = {}
    edges = "Source;Target;Weight"
    default_weight = 100
    index_days = 0
    index_sha1 = 0
    prev_id = None 
    delta = timedelta(days=1)
    while start_date <= end_date:
        # create day id
        id_current = f"d{index_days}"
        index_days += 1
        # add day to the nodes
        nodes += f"\n{id_current};{start_date.strftime('%Y-%m-%d')}"
        # create a link between current day and previous day if there is one
        if prev_id:
            edges += f"\n{prev_id};{id_current};{default_weight}"
        # get all sha1 at this date and group them by sha1
        images_at_this_date = df.loc[df['created_at'] == start_date].groupby('sha1', as_index=False).count()
        if not images_at_this_date.empty:
            # for each sha1 at this date
            for index, line in images_at_this_date.iterrows():
                # create an id only if the node does not already exist
                sha1 = line['sha1']
                if sha1 in nodes_dic:
                    id_sha1 = nodes_dic[sha1]
                else:
                    id_sha1 = f"s{index_sha1}"
                    nodes += f"\n{id_sha1};{sha1}"
                    index_sha1 += 1
                # add an edge between the day and the sha1 with weight = nb of occurences that day
                edges += f"\n{id_current};{id_sha1};{line['created_at']}"
        # increment date                             
        start_date += delta
        # save current_id
        prev_id = id_current
    return nodes, edges

In [44]:
nodes, edges = build_skeletton(df)
with open(os.path.join(path, 'nodes.csv'), 'w') as f:
    f.write(nodes)
with open(os.path.join(path, 'edges.csv'), 'w') as f:
    f.write(edges)